import 'reflect-metadata'


export const DI_CONTAINER_CREATOR_CONSTRUCTOR: symbol = Symbol('LAKUTATA.DI.CONTAINER.CREATOR.CONSTRUCTOR')
export const DI_CONTAINER_INJECT_PROPERTIES: symbol = Symbol('LAKUTATA.DI.CONTAINER.INJECT.PROPERTIES')
export const DI_CONTAINER_INJECT_IS_MODULE_GETTER_KEY: symbol = Symbol('LAKUTATA.DI.CONTAINER.INJECT.IS.MODULE.GETTER.KEY')
export const DI_CONTAINER_INJECT_IS_MODULE_GETTER: symbol = Symbol('LAKUTATA.DI.CONTAINER.INJECT.IS.MODULE.GETTER')
export const DI_CONTAINER_SPECIAL_INJECT_APP_GETTER_KEY: symbol = Symbol('LAKUTATA.DI.CONTAINER.SPECIAL.INJECT.APP.GETTER.KEY')
export const DI_CONTAINER_SPECIAL_INJECT_APP_GETTER: symbol = Symbol('LAKUTATA.DI.CONTAINER.SPECIAL.INJECT.APP.GETTER')
export const DI_CONTAINER_SPECIAL_INJECT_MODULE_GETTER: symbol = Symbol('LAKUTATA.DI.CONTAINER.SPECIAL.INJECT.MODULE.GETTER')
export const DI_TARGET_CONSTRUCTOR_LIFETIME: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.LIFETIME')
export const DI_TARGET_CONSTRUCTOR_LIFETIME_LOCK: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.LIFETIME.LOCK')
export const DI_TARGET_CONSTRUCTOR_INJECTS: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.INJECTS')
export const DI_TARGET_CONSTRUCTOR_SPECIAL_INJECTS: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.SPECIAL.INJECTS')

//new metadata keys
export const DI_TARGET_CONSTRUCTOR_CONFIGURABLE_PROPERTIES: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.CONFIGURABLE.PROPERTIES')
export const DI_TARGET_CONSTRUCTOR_SYMBOL: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.SYMBOL')
export const DI_TARGET_CONSTRUCTOR_AUTOLOAD: symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.AUTOLOAD')
export const DI_TARGET_CONTAINER: symbol = Symbol('LAKUTATA.DI.TARGET.CONTAINER')
export const DI_CONTAINER_NEW_TRANSIENT_CALLBACK: symbol = Symbol('LAKUTATA.DI.CONTAINER.NEW.TRANSIENT.CALLBACK')



