export const DTO_CLASS: Symbol = Symbol('LAKUTATA.DTO.CLASS')
export const DTO_SCHEMAS: Symbol = Symbol('LAKUTATA.DTO.SCHEMAS')

export const DI_CONTAINER_CREATOR_CONSTRUCTOR: Symbol = Symbol('LAKUTATA.DI.CONTAINER.CREATOR.CONSTRUCTOR')
export const DI_TARGET_CONSTRUCTOR_INJECTS: Symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.INJECTS')
export const DI_TARGET_CONSTRUCTOR_CONFIGURABLE_ITEMS: Symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.CONFIGURABLE.ITEMS')
export const DI_TARGET_CONSTRUCTOR_CONFIGURABLE_OBJECT: Symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.CONFIGURABLE.OBJECT')
export const DI_TARGET_CONSTRUCTOR_UNIQUE_MARK: Symbol = Symbol('LAKUTATA.DI.TARGET.CONSTRUCTOR.UNIQUE.MARK')

export const OBJECT_INIT_MARK: Symbol = Symbol('LAKUTATA.OBJECT.INIT.MARK')
