import 'reflect-metadata'

export const OBJECT_INIT_MARK: symbol = Symbol('LAKUTATA.OBJECT.INIT.MARK')

export const CONTROLLER_CONSTRUCTOR_MARK: symbol = Symbol('LAKUTATA.CONTROLLER.CONSTRUCTOR.MARK')
export const CONTROLLER_ACTION_MAP: symbol = Symbol('LAKUTATA.CONTROLLER.ACTION.MAP')
export const CONTROLLER_PATTERN_MANAGER: symbol = Symbol('LAKUTATA.CONTROLLER.PATTERN.MANAGER')
export const CONTROLLER_AUTH_MAP: symbol = Symbol('LAKUTATA.CONTROLLER.AUTH.MAP')

export const MODEL_PROPERTY_MAP: symbol = Symbol('LAKUTATA.MODEL.PROPERTY.MAP')
