export enum CType {
    /**
     * Standard types
     */
    void = 'void',
    int8 = 'int8',
    int8_t = 'int8_t',
    uint8 = 'uint8',
    uint8_t = 'uint8_t',
    char = 'char',
    uchar = 'uchar',
    unsigned_char = 'unsigned char',
    char16 = 'char16',
    char16_t = 'char16_t',
    int16 = 'int16',
    int16_t = 'int16_t',
    uint16 = 'uint16',
    uint16_t = 'uint16_t',
    short = 'short',
    ushort = 'ushort',
    unsigned_short = 'unsigned short',
    int32 = 'int32',
    int32_t = 'int32_t',
    uint32 = 'uint32',
    uint32_t = 'uint32_t',
    int = 'int',
    uint = 'uint',
    unsigned_int = 'unsigned int',
    int64 = 'int64',
    int64_t = 'int64_t',
    uint64 = 'uint64',
    uint64_t = 'uint64_t',
    longlong = 'longlong',
    long_long = 'long long',
    ulonglong = 'ulonglong',
    unsigned_long_long = 'unsigned long long',
    float32 = 'float32',
    float64 = 'float64',
    float = 'float',
    double = 'double',
    /**
     * Size changeable types
     */
    bool = 'bool',
    long = 'long',
    ulong = 'ulong',
    unsigned_long = 'unsigned long',
    intptr = 'intptr',
    intptr_t = 'intptr_t',
    uintptr = 'uintptr',
    uintptr_t = 'uintptr_t',
    str = 'str',
    string = 'string',
    str16 = 'str16',
    string16 = 'string16',
    /**
     * Endian-sensitive integers
     */
    int16_le = 'int16_le',
    int16_le_t = 'int16_le_t',
    int16_be = 'int16_be',
    int16_be_t = 'int16_be_t',
    uint16_le = 'uint16_le',
    uint16_le_t = 'uint16_le_t',
    uint16_be = 'uint16_be',
    uint16_be_t = 'uint16_be_t',
    int32_le = 'int32_le',
    int32_le_t = 'int32_le_t',
    int32_be = 'int32_be',
    int32_be_t = 'int32_be_t',
    uint32_le = 'uint32_le',
    uint32_le_t = 'uint32_le_t',
    uint32_be = 'uint32_be',
    uint32_be_t = 'uint32_be_t',
    int64_le = 'int64_le',
    int64_le_t = 'int64_le_t',
    int64_be = 'int64_be',
    int64_be_t = 'int64_be_t',
    uint64_le = 'uint64_le',
    uint64_le_t = 'uint64_le_t',
    uint64_be = 'uint64_be',
    uint64_be_t = 'uint64_be_t'
}
